name: wp

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060
    env_file:
      - stack.env
  wordpress:
    image: wordpress:6.4.0
    ports:
      - 80:80
    restart: always
    env_file:
      - stack.env
volumes:
  db_data:

